name: CI

permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Run pre-commit checks
        run: |
          set -e
          pip install pre-commit
          pre-commit run --verbose --all-files
  tests:
    runs-on: ubuntu-latest
    env:
      # Temporarily disable sharded repodata until fixed upstream.
      MAMBA_USE_SHARDED_REPODATA: "false"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Free extra disk space
        uses: jlumbroso/free-disk-space@main
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: conda-incubator/setup-miniconda@fc2d68f6413eb2d87b895e92f8584b5b94a10167 # v3.3.0
        with:
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          environment-file: environment.yml
      - name: Install RetroChimera
        run: |
          pip install .[all]
      - name: Run pytest
        run: |
          coverage run -p -m pytest \
            --verbose \
            --durations=50 \
            --durations-min=1.0
          coverage combine
          coverage report
